# Generated by Django 4.0.5 on 2022-06-30 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_projects_contributors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contributors",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="projects",
            old_name="author_user_id",
            new_name="author_user",
        ),
        migrations.RemoveField(
            model_name="projects",
            name="project_id",
        ),
        migrations.AddField(
            model_name="contributors",
            name="project",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_of_contributor",
                to="projects.projects",
            ),
        ),
        migrations.AddField(
            model_name="projects",
            name="contributors",
            field=models.ManyToManyField(
                related_name="contributors_of_project",
                through="projects.Contributors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="type",
            field=models.CharField(
                choices=[
                    ("BE", "Back-End"),
                    ("FE", "Front-End"),
                    ("IO", "iOs"),
                    ("AN", "Android"),
                ],
                help_text="Type du projet (back-end, front-end, iOS ou Android).",
                max_length=2,
            ),
        ),
        migrations.CreateModel(
            name="Issues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Titre du problème.", max_length=128),
                ),
                (
                    "desc",
                    models.CharField(
                        help_text="Description du problème.", max_length=128
                    ),
                ),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("BUG", "BUG"),
                            ("UP", "AMÉLIORATION"),
                            ("TASK", "TÂCHE"),
                        ],
                        help_text="Balise du problème (BUG, AMÉLIORATION ou TÂCHE).",
                        max_length=4,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "FAIBLE"),
                            ("MOY", "MOYENNE"),
                            ("HIGH", "ÉLEVÉE"),
                        ],
                        help_text="Priorité du problème (FAIBLE, MOYENNE ou ÉLEVÉE).",
                        max_length=4,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TODO", "À FAIRE"),
                            ("RUN", "EN COURS"),
                            ("DONE", "TERMINÉ"),
                        ],
                        help_text="Statut du problème (À faire, En cours ou Terminé).",
                        max_length=4,
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "assignee_user",
                    models.ForeignKey(
                        default=models.ForeignKey(
                            on_delete=django.db.models.deletion.CASCADE,
                            related_name="Issue_author",
                            to=settings.AUTH_USER_MODEL,
                        ),
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Issue_assignee_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Issue_author",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.projects",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Description du commentaire.", max_length=2048
                    ),
                ),
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "author_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.issues",
                    ),
                ),
            ],
        ),
    ]
